# SITE CONFIGURATION
title: sganachari # your site title
author: Sravan Ganachari # You :P
description: > # Meta description of Homepage
  Blog on thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sganachari.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sravan Ganachari
  links:
    - https://twitter.com/sravan_g
    - https://www.linkedin.com/in/sravan-ganachari-39902216/
    - https://github.com/sganachari


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: sravan.g@gmail.com # email for form submission

twitter_username: sravan_g # replace with your_twitter_username or comment to remove link from footer
github_username:  sganachari # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  comments: true
  shortname: disqus_bHzuoLhogI # to enable comments replace with your_disqus_shortname

google_tag_manager: G-E06KRZ9HZ7 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
